import {
  AcademicCapIcon,
  AdjustmentsHorizontalIcon,
  AdjustmentsVerticalIcon,
  ArchiveBoxIcon,
  ArrowDownIcon,
  ArrowDownCircleIcon,
  ArrowDownLeftIcon,
  ArrowDownOnSquareIcon,
  ArrowDownRightIcon,
  ArrowDownTrayIcon,
  ArrowLeftIcon,
  ArrowLeftCircleIcon,
  ArrowLongDownIcon,
  ArrowLongLeftIcon,
  ArrowLongRightIcon,
  ArrowLongUpIcon,
  ArrowPathIcon,
  ArrowRightIcon,
  ArrowRightCircleIcon,
  ArrowRightOnRectangleIcon,
  ArrowUpIcon,
  ArrowUpCircleIcon,
  ArrowUturnDownIcon,
  ArrowUturnLeftIcon,
  ArrowUturnRightIcon,
  ArrowUturnUpIcon,
  AtSymbolIcon,
  BackspaceIcon,
  BackwardIcon,
  BanknotesIcon,
  Bars2Icon,
  Bars3Icon,
  Bars3BottomLeftIcon,
  Bars3BottomRightIcon,
  Bars3CenterLeftIcon,
  Bars4Icon,
  BarsArrowDownIcon,
  BarsArrowUpIcon,
  Battery0Icon,
  Battery100Icon,
  Battery50Icon,
  BeakerIcon,
  BellIcon,
  BellAlertIcon,
  BellSlashIcon,
  BellSnoozeIcon,
  BoltIcon,
  BoltSlashIcon,
  BookOpenIcon,
  BookmarkIcon,
  BookmarkSlashIcon,
  BookmarkSquareIcon,
  BriefcaseIcon,
  BugAntIcon,
  BuildingLibraryIcon,
  BuildingOfficeIcon,
  BuildingOffice2Icon,
  BuildingStorefrontIcon,
  CakeIcon,
  CalculatorIcon,
  CalendarIcon,
  CameraIcon,
  ChartBarIcon,
  ChartPieIcon,
  ChatBubbleBottomCenterIcon,
  ChatBubbleBottomCenterTextIcon,
  ChatBubbleLeftIcon,
  ChatBubbleLeftEllipsisIcon,
  CheckIcon,
  CheckBadgeIcon,
  CheckCircleIcon,
  ChevronDoubleDownIcon,
  ChevronDoubleLeftIcon,
  ChevronDoubleRightIcon,
  ChevronDoubleUpIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  CircleStackIcon,
  ClipboardIcon,
  ClipboardDocumentIcon,
  ClipboardDocumentCheckIcon,
  ClipboardDocumentListIcon,
  ClockIcon,
  CloudIcon,
  CloudArrowDownIcon,
  CloudArrowUpIcon,
  CodeBracketIcon,
  CodeBracketSquareIcon,
  CogIcon,
  ComputerDesktopIcon,
  CpuChipIcon,
  CreditCardIcon,
  CubeIcon,
  CurrencyDollarIcon,
  DevicePhoneMobileIcon,
  DocumentIcon,
  DocumentArrowDownIcon
} from "@heroicons/react/24/outline";

export const iconOptions = [
  { label: "AcademicCap", value: "academicCap", icon: AcademicCapIcon },
  { label: "AdjustmentsHorizontal", value: "adjustmentsHorizontal", icon: AdjustmentsHorizontalIcon },
  { label: "AdjustmentsVertical", value: "adjustmentsVertical", icon: AdjustmentsVerticalIcon },
  { label: "ArchiveBox", value: "archiveBox", icon: ArchiveBoxIcon },
  { label: "ArrowDown", value: "arrowDown", icon: ArrowDownIcon },
  { label: "ArrowDownCircle", value: "arrowDownCircle", icon: ArrowDownCircleIcon },
  { label: "ArrowDownLeft", value: "arrowDownLeft", icon: ArrowDownLeftIcon },
  { label: "ArrowDownOnSquare", value: "arrowDownOnSquare", icon: ArrowDownOnSquareIcon },
  { label: "ArrowDownRight", value: "arrowDownRight", icon: ArrowDownRightIcon },
  { label: "ArrowDownTray", value: "arrowDownTray", icon: ArrowDownTrayIcon },
  { label: "ArrowLeft", value: "arrowLeft", icon: ArrowLeftIcon },
  { label: "ArrowLeftCircle", value: "arrowLeftCircle", icon: ArrowLeftCircleIcon },
  { label: "ArrowLongDown", value: "arrowLongDown", icon: ArrowLongDownIcon },
  { label: "ArrowLongLeft", value: "arrowLongLeft", icon: ArrowLongLeftIcon },
  { label: "ArrowLongRight", value: "arrowLongRight", icon: ArrowLongRightIcon },
  { label: "ArrowLongUp", value: "arrowLongUp", icon: ArrowLongUpIcon },
  { label: "ArrowPath", value: "arrowPath", icon: ArrowPathIcon },
  { label: "ArrowRight", value: "arrowRight", icon: ArrowRightIcon },
  { label: "ArrowRightCircle", value: "arrowRightCircle", icon: ArrowRightCircleIcon },
  { label: "ArrowRightOnRectangle", value: "arrowRightOnRectangle", icon: ArrowRightOnRectangleIcon },
  { label: "ArrowUp", value: "arrowUp", icon: ArrowUpIcon },
  { label: "ArrowUpCircle", value: "arrowUpCircle", icon: ArrowUpCircleIcon },
  { label: "ArrowUturnDown", value: "arrowUturnDown", icon: ArrowUturnDownIcon },
  { label: "ArrowUturnLeft", value: "arrowUturnLeft", icon: ArrowUturnLeftIcon },
  { label: "ArrowUturnRight", value: "arrowUturnRight", icon: ArrowUturnRightIcon },
  { label: "ArrowUturnUp", value: "arrowUturnUp", icon: ArrowUturnUpIcon },
  { label: "AtSymbol", value: "atSymbol", icon: AtSymbolIcon },
  { label: "Backspace", value: "backspace", icon: BackspaceIcon },
  { label: "Backward", value: "backward", icon: BackwardIcon },
  { label: "Banknotes", value: "banknotes", icon: BanknotesIcon },
  { label: "Bars2", value: "bars2", icon: Bars2Icon },
  { label: "Bars3", value: "bars3", icon: Bars3Icon },
  { label: "Bars3BottomLeft", value: "bars3BottomLeft", icon: Bars3BottomLeftIcon },
  { label: "Bars3BottomRight", value: "bars3BottomRight", icon: Bars3BottomRightIcon },
  { label: "Bars3CenterLeft", value: "bars3CenterLeft", icon: Bars3CenterLeftIcon },
  { label: "Bars4", value: "bars4", icon: Bars4Icon },
  { label: "BarsArrowDown", value: "barsArrowDown", icon: BarsArrowDownIcon },
  { label: "BarsArrowUp", value: "barsArrowUp", icon: BarsArrowUpIcon },
  { label: "Battery0", value: "battery0", icon: Battery0Icon },
  { label: "Battery100", value: "battery100", icon: Battery100Icon },
  { label: "Battery50", value: "battery50", icon: Battery50Icon },
  { label: "Beaker", value: "beaker", icon: BeakerIcon },
  { label: "Bell", value: "bell", icon: BellIcon },
  { label: "BellAlert", value: "bellAlert", icon: BellAlertIcon },
  { label: "BellSlash", value: "bellSlash", icon: BellSlashIcon },
  { label: "BellSnooze", value: "bellSnooze", icon: BellSnoozeIcon },
  { label: "Bolt", value: "bolt", icon: BoltIcon },
  { label: "BoltSlash", value: "boltSlash", icon: BoltSlashIcon },
  { label: "BookOpen", value: "bookOpen", icon: BookOpenIcon },
  { label: "Bookmark", value: "bookmark", icon: BookmarkIcon },
  { label: "BookmarkSlash", value: "bookmarkSlash", icon: BookmarkSlashIcon },
  { label: "BookmarkSquare", value: "bookmarkSquare", icon: BookmarkSquareIcon },
  { label: "Briefcase", value: "briefcase", icon: BriefcaseIcon },
  { label: "BugAnt", value: "bugAnt", icon: BugAntIcon },
  { label: "BuildingLibrary", value: "buildingLibrary", icon: BuildingLibraryIcon },
  { label: "BuildingOffice", value: "buildingOffice", icon: BuildingOfficeIcon },
  { label: "BuildingOffice2", value: "buildingOffice2", icon: BuildingOffice2Icon },
  { label: "BuildingStorefront", value: "buildingStorefront", icon: BuildingStorefrontIcon },
  { label: "Cake", value: "cake", icon: CakeIcon },
  { label: "Calculator", value: "calculator", icon: CalculatorIcon },
  { label: "Calendar", value: "calendar", icon: CalendarIcon },
  { label: "Camera", value: "camera", icon: CameraIcon },
  { label: "ChartBar", value: "chartBar", icon: ChartBarIcon },
  { label: "ChartPie", value: "chartPie", icon: ChartPieIcon },
  { label: "ChatBubbleBottomCenter", value: "chatBubbleBottomCenter", icon: ChatBubbleBottomCenterIcon },
  { label: "ChatBubbleBottomCenterText", value: "chatBubbleBottomCenterText", icon: ChatBubbleBottomCenterTextIcon },
  { label: "ChatBubbleLeft", value: "chatBubbleLeft", icon: ChatBubbleLeftIcon },
  { label: "ChatBubbleLeftEllipsis", value: "chatBubbleLeftEllipsis", icon: ChatBubbleLeftEllipsisIcon },
  { label: "Check", value: "check", icon: CheckIcon },
  { label: "CheckBadge", value: "checkBadge", icon: CheckBadgeIcon },
  { label: "CheckCircle", value: "checkCircle", icon: CheckCircleIcon },
  { label: "ChevronDoubleDown", value: "chevronDoubleDown", icon: ChevronDoubleDownIcon },
  { label: "ChevronDoubleLeft", value: "chevronDoubleLeft", icon: ChevronDoubleLeftIcon },
  { label: "ChevronDoubleRight", value: "chevronDoubleRight", icon: ChevronDoubleRightIcon },
  { label: "ChevronDoubleUp", value: "chevronDoubleUp", icon: ChevronDoubleUpIcon },
  { label: "ChevronDown", value: "chevronDown", icon: ChevronDownIcon },
  { label: "ChevronLeft", value: "chevronLeft", icon: ChevronLeftIcon },
  { label: "ChevronRight", value: "chevronRight", icon: ChevronRightIcon },
  { label: "ChevronUp", value: "chevronUp", icon: ChevronUpIcon },
  { label: "CircleStack", value: "circleStack", icon: CircleStackIcon },
  { label: "Clipboard", value: "clipboard", icon: ClipboardIcon },
  { label: "ClipboardDocument", value: "clipboardDocument", icon: ClipboardDocumentIcon },
  { label: "ClipboardDocumentCheck", value: "clipboardDocumentCheck", icon: ClipboardDocumentCheckIcon },
  { label: "ClipboardDocumentList", value: "clipboardDocumentList", icon: ClipboardDocumentListIcon },
  { label: "Clock", value: "clock", icon: ClockIcon },
  { label: "Cloud", value: "cloud", icon: CloudIcon },
  { label: "CloudArrowDown", value: "cloudArrowDown", icon: CloudArrowDownIcon },
  { label: "CloudArrowUp", value: "cloudArrowUp", icon: CloudArrowUpIcon },
  { label: "CodeBracket", value: "codeBracket", icon: CodeBracketIcon },
  { label: "CodeBracketSquare", value: "codeBracketSquare", icon: CodeBracketSquareIcon },
  { label: "Cog", value: "cog", icon: CogIcon },
  { label: "ComputerDesktop", value: "computerDesktop", icon: ComputerDesktopIcon },
  { label: "CpuChip", value: "cpuChip", icon: CpuChipIcon },
  { label: "CreditCard", value: "creditCard", icon: CreditCardIcon },
  { label: "Cube", value: "cube", icon: CubeIcon },
  { label: "CurrencyDollar", value: "currencyDollar", icon: CurrencyDollarIcon },
  { label: "DevicePhoneMobile", value: "devicePhoneMobile", icon: DevicePhoneMobileIcon },
  { label: "Document", value: "document", icon: DocumentIcon },
  { label: "DocumentArrowDown", value: "documentArrowDown", icon: DocumentArrowDownIcon }
];
